### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 179: character maps to <undefined>

### ISSUE THREAD

**Issue by saurabhbidwai** [miendinh/VietnameseOCR#4]
E:\Shezartech\OCR\Vietnamese\VietnameseOCR-master>python predict.py
Done shuffle dataset!
Traceback (most recent call last):
  File "predict.py", line 31, in <module>
    characters = DataGenerator().get_list_characters()
  File "E:\Shezartech\OCR\Vietnamese\VietnameseOCR-master\generate_dataset.py", line 35, in get_list_characters
    for r in cf:
  File "C:\Users\DELL\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 179: character maps to <undefined>

**Comment by saurabhbidwai** [comment]
make chnages in generate_dataset.py as follows at line 34 - 
with open(CHARACTERS_SET, encoding="utf8") as cf:

refer-
https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character
